$schema: "https://json-schema.org/draft/2020-12/schema"
$id: https://raw.githubusercontent.com/markschl/uvsnake/main/workflow/config.schema.yaml
description: USEARCH/VSEARCH-based amplicon pipeline configuration
properties:

  defaults:
    type: object
    properties:
      program:
        type: string
        enum: [vsearch, usearch]
      maxaccepts:
        type: integer
        minimum: 1
        default: 1
      maxrejects:
        type: integer
        minimum: 1
        default: 1

  usearch_binary:
    type: string
    default: usearch
    description:
        USEARCH binary name/path (download from https://drive5.com/usearch).
        The default is 'usearch', assuming that the program is accessible
        in $PATH. Alternatively, an absolute or relative path
        (relative to analysis directory containing 'config') can be
        specified.

  sample_file:
    type: string
    description: >
      Path to a sample file with one forward   
    additionalProperties: false
    default: config/samples.tsv

  primers:
    type: object
    properties:
      trim_settings:
        type: object
        properties:
          min_overlap:
            type: integer
            minimum: 5
          max_error_rate:
            type: number
            exclusiveMinimum: 0
            maximum: 1
          min_length:
            type: integer
            minimum: 1
        required: [min_overlap, max_error_rate, min_length]
        additionalProperties: false
    if:
      required: [trim_settings]
    else:
      patternProperties:
        ^(\w+)$:
          type: object
          properties:
            forward:
              type: array
              items:
                type: object
                patternProperties:
                  ^(\w+)$:
                    type: string
              minItems: 1
            reverse:
              type: array
              items:
                type: object
                patternProperties:
                  ^(\w+)$:
                    type: string
              minItems: 1
            combinations:
              oneOf:
                - { type: string, enum: [all] }
                - 
                  type: array
                  items: { type: string }
                  minItems: 1
              default: all
          required: [forward, reverse]
          additionalProperties: false
      minProperties: 1
      additionalProperties: false

  merge:
    type: object
    properties:
      overlap_ident:
        type: integer
        minimum: 0
        maximum: 100
      max_diffs:
        type: integer
        minimum: 0
      program: { $ref: "#/properties/defaults/properties/program" }
    required: [overlap_ident, max_diffs]
    additionalProperties: false
  
  filter:
    type: object
    properties:
      max_error_rate:
        type: number
        minimum: 0
        maximum: 1
    required: [max_error_rate]
    additionalProperties: false
  
  unoise3:
    type: object
    properties:
      min_size:
        type: integer
        minimum: 1
      program: { $ref: "#/properties/defaults/properties/program" }
      maxaccepts: { $ref: "#/properties/defaults/properties/maxaccepts" }
      maxrejects: { $ref: "#/properties/defaults/properties/maxrejects" }
    required: [min_size]
    additionalProperties: false
  
  uparse:
    type: object
    properties:
      min_size:
        type: integer
        minimum: 1
        default: 2
      program: { $ref: "#/properties/defaults/properties/program" }
      maxaccepts: { $ref: "#/properties/defaults/properties/maxaccepts" }
      maxrejects: { $ref: "#/properties/defaults/properties/maxrejects" }
    required: [min_size]
    additionalProperties: false
  
  otutab:
    type: object
    properties:
      ident_threshold:
        type: number
        minimum: 2
        maximum: 100
        description:
          (number, percent) Identity threshold used for constructing the OTU 
          table by comparing the (unfiltered) sequencing reads against the
          OTUs. The minimum is 2 in order to prevent the accidental use of
          fractional identity (which is actually internally used and may
          be familiar to users of USEARCH/VSEARCH.
      extra:
        type: boolean
        default: false
        description:
          (boolean) Creates additional diagnostic output files;
          (1) a mapping with three columns (read name, Zotu name, percent identity)
          deposited in workdir/cluster/4_otutab/<primers>/<unoise3/uparse>_search.txt.gz,
          and
          (2) in case of using VSEARCH a BAM file that allows inspecting the
          mapped reads.
      program: { $ref: "#/properties/defaults/properties/program" }
      maxaccepts: { $ref: "#/properties/defaults/properties/maxaccepts" }
      maxrejects: { $ref: "#/properties/defaults/properties/maxrejects" }
    required: [ident_threshold]
    additionalProperties: false

  # post_cluster:
  #   type: object
  #   properties:
  #     ident_threshold:
  #       type: number
  #       minimum: 2
  #       maximum: 100
  #     program: { $ref: "#/properties/defaults/properties/program" }
  #     maxaccepts:
  #       type: integer
  #       minimum: 1
  #       default: 64
  #     maxrejects:
  #       type: integer
  #       minimum: 1
  #       default: 64
  #   required: [ident_threshold]
  #   additionalProperties: false

  sintax:
    type: object
    properties:
      db:
        type: string
      db_format:
        type: string
      confidence:
        type: number
        minimum: 0
        maximum: 1
      program: { $ref: "#/properties/defaults/properties/program" }
      maxaccepts: { $ref: "#/properties/defaults/properties/maxaccepts" }
      maxrejects: { $ref: "#/properties/defaults/properties/maxrejects" }
    required: [db, db_format, confidence]
    additionalProperties: false

additionalProperties: false

required: [defaults, primers, merge, filter, otutab]
