$schema: "https://json-schema.org/draft/2020-12/schema"
$id: https://raw.githubusercontent.com/markschl/uvsnake/main/workflow/config.schema.yaml
description: USEARCH/VSEARCH-based amplicon pipeline configuration
properties:

  program:
    type: string
    enum: [vsearch, usearch]
    description:
      The program (USEARCH or VSEARCH) to use by default for all commands.
      This can be overridden by the 'program' setting of commands.

  usearch_binary:
    type: string
    description:
        Path to a custom USEARCH binary that should be used instead
        of v12 beta (download from https://drive5.com/usearch,
        respectively https://github.com/rcedgar/usearch_old_binaries).

  sample_file:
    type: string
    description: >
      Path to a sample file with one forward   
    additionalProperties: false
    default: config/samples.tsv

  primers:
    type: object
    properties:
      trim_settings:
        type: object
        properties:
          min_overlap:
            type: integer
            minimum: 5
          max_error_rate:
            type: number
            exclusiveMinimum: 0
            maximum: 1
          min_length:
            type: integer
            minimum: 1
        required: [min_overlap, max_error_rate, min_length]
        additionalProperties: false
    if:
      required: [trim_settings]
    else:
      patternProperties:
        ^(\w+)$:
          type: object
          properties:
            forward:
              type: array
              items:
                type: object
                patternProperties:
                  ^(\w+)$:
                    type: string
              minItems: 1
            reverse:
              type: array
              items:
                type: object
                patternProperties:
                  ^(\w+)$:
                    type: string
              minItems: 1
            combinations:
              type: array
              items: { type: string }
              minItems: 1
          required: [forward, reverse]
          additionalProperties: false
      minProperties: 1
      additionalProperties: false

  merge:
    type: object
    properties:
      overlap_ident:
        type: integer
        minimum: 0
        maximum: 100
      max_diffs:
        type: integer
        minimum: 0
      program: { $ref: "#/properties/program" }
    required: [overlap_ident, max_diffs]
    additionalProperties: false
  
  filter:
    type: object
    properties:
      max_error_rate:
        type: number
        minimum: 0
        maximum: 1
    required: [max_error_rate]
    additionalProperties: false
  
  unoise3:
    type: object
    properties:
      min_size:
        type: integer
        minimum: 1
      program: { $ref: "#/properties/program" }
      maxaccepts:
        type: integer
        minimum: 1
        default: 1
        description:
          This termination option seems unused or without effect in VSEARCH.
          Changing it also has little impact on performance and results of USEARCH.
      maxrejects:
        type: integer
        minimum: 1
        default: 32  # default in VSEARCH, not used by USEARCH
        description: This termination option not used by USEARCH (but by VSEARCH).
    required: [min_size]
    additionalProperties: false
  
  uparse:
    type: object
    properties:
      min_size:
        type: integer
        minimum: 1
        default: 2
      program: { $ref: "#/properties/program" }
      maxaccepts:
        type: integer
        minimum: 1
        default: 1  # default in USEARCH v12
      maxrejects:
        type: integer
        minimum: 1
        default: 32  # default in USEARCH v12
        description: This termination option has a neglectable impact on speed
    required: [min_size]
    additionalProperties: false
  
  otutab:
    type: object
    properties:
      ident_threshold:
        type: number
        minimum: 2
        maximum: 100
        description:
          (number, percent) Identity threshold used for constructing the OTU 
          table by comparing the (unfiltered) sequencing reads against the
          OTUs. The minimum is 2 in order to prevent the accidental use of
          fractional identity (which is actually internally used and may
          be familiar to users of USEARCH/VSEARCH.
      extra:
        type: boolean
        default: false
        description:
          (boolean) Creates additional diagnostic output files;
          (1) a mapping with three columns (read name, Zotu name, percent identity)
          deposited in workdir/cluster/4_otutab/<primers>/<unoise3/uparse>_search.txt.gz,
          and
          (2) in case of using VSEARCH a BAM file that allows inspecting the
          mapped reads.
      program: { $ref: "#/properties/program" }
      # references: https://rcedgar.github.io/usearch12_documentation/termination_options.html
      # and https://github.com/rcedgar/usearch12/blob/master/src/terminator.cpp
      maxaccepts:
        type: integer
        minimum: 1
        default: 8
        description:
          The default of this termination option is 8 in USEARCH v11 and 4 in v10.
      maxrejects:
        type: integer
        minimum: 1
        default: 256
        description:
          The default of this termination option is 256 in USEARCH v11 and 64 in v10.
    required: [ident_threshold]
    additionalProperties: false

  # post_cluster:
  #   type: object
  #   properties:
  #     ident_threshold:
  #       type: number
  #       minimum: 2
  #       maximum: 100
  #     program: { $ref: "#/properties/program" }
  #     maxaccepts:
  #       type: integer
  #       minimum: 1
  #       default: 64
  #     maxrejects:
  #       type: integer
  #       minimum: 1
  #       default: 64
  #   required: [ident_threshold]
  #   additionalProperties: false

  sintax:
    type: object
    properties:
      db:
        type: string
      db_format:
        type: string
      confidence:
        type: number
        minimum: 0
        maximum: 1
      program: { $ref: "#/properties/program" }
      strand:
        type: string
        enum: [both, plus]
        default: both
        description:
          Search on both strands ('both') or only the forward strand ('plus'),
          which is faster. If you are sure that all database sequences
          have the same orientation, 'plus' can be specified, otherwise
          the default of 'both' will be used.
      rand_seed:
        type: integer
        minimum: 0
        default: 0
        description:
          Random seed to ensure reproducibility (VSEARCH only). The seed must
          be > 0, and it should be noted that multi-threaded taxonomic assignment
          is not possible with this option, only a single thread is used.
    patternProperties:
      ^[^\s]+\.\.\.[^\s]+$:
        type: object
        properties:
          db:
            type: string
          db_format:
            type: string
          confidence:
            type: number
            minimum: 0
            maximum: 1
          program: { $ref: "#/properties/program" }
          strand:
            type: string
            enum: [both, plus]
            default: both
          rand_seed:
            type: integer
            minimum: 0
            default: 0
    additionalProperties: false

additionalProperties: false

required: [program, primers, merge, filter, otutab]
