from snakemake.utils import min_version, validate

# we require the Bash script functionality
# https://github.com/snakemake/snakemake/blob/main/CHANGELOG.md
min_version("7.14.0")

configfile: "config/config.yaml"

validate(config, "config.schema.yaml")

report: "report/workflow.rst"

include: "rules/common.smk"
include: "rules/clean.smk"


# Initialize regular pipeline there is valid sample file.
# This allows using this workflow as module
# (where schema validation can be skipped)
if "_input" in config:

    include: "rules/qc.smk"
    include: "rules/stats.smk"
    include: "rules/prepare_paired.smk"
    include: "rules/cluster_resources.smk"
    include: "rules/cluster.smk"
    include: "rules/other.smk"
    include: "rules/targets.smk"


include: "rules/taxonomy.smk"
