from snakemake.utils import min_version
from snakemake.utils import validate

# we require the Bash script functionality
# https://github.com/snakemake/snakemake/blob/main/CHANGELOG.md
min_version("7.14.0")


##### configuration #####

configfile: "config/config.yaml"

validate(config, "config.schema.yaml")
# from pprint import pprint; pprint(config)


##### load rules #####

include: "rules/common.smk"
include: "rules/clean.smk"

# Initialize regular pipeline if configuration is present.
# This allows using this workflow as module
# (where schema validation can be skipped)
if "input" in config and "primers" in config:
    include: "rules/other.smk"
    include: "rules/qc.smk"
    include: "rules/prepare_paired.smk"
    include: "rules/cluster.smk"
    include: "rules/targets.smk"

if "sintax" in config:
    include: "rules/taxonomy.smk"
