
program: usearch

primers:
  forward:
    - ITS3-KYO2:
        GATGAAGAACGYAGYRAA,
        GATGAAGRACGCMGCGAA,
        GATGACGAACGCAGCGAA,
        GATGAAGAACACAGYGAA,
        GATGAAGAGCGYAGCRAA,
        GATGAAGAACGCGGCGAA,
        TCGATGAAGAMCGTWGC
  reverse:
    - ITS4:
        TCCTCCGCTTATTGATATGC,
        TCCTCCGCTTATTAATATGC,
        TCCTCCGCTTAVTGATATGC,
        TCCTCCACTTATTGATATGC,
        TCCTCTGCTTATTGATATGC,
        TCCTGCGCTTATTGATATGC,
        TCCTCCGCTGAWTAATATGC,
        TCCTCGCCTTATTGATATGC
  trim_settings:
    min_overlap: 15
    max_error_rate: 0.1
    min_length: 100

merge:
  overlap_ident: 75
  max_diffs: 1000

filter:
  max_error_rate: 0.002

uparse:
  min_size: 2

unoise3:
  min_size: 3

otutab:
  ident_threshold: 97

sintax:
  db: unite_refs.fasta.gz
  db_format: qiime
  confidence: 0.7
  rand_seed: 9401
