# Simple configuration template
# see https://github.com/markschl/uvsnake/blob/main/config/README.md
# for more information

# (optional: change program globally)
# program: vsearch

primers:
  forward:
    - fwd_primer: SEQUENCE1, SEQUENCE2
  reverse:
    - rev_primer: SEQUENCE
  trim_settings:
    min_overlap: 15
    max_error_rate: 0.1
    min_length: 100

merge:
  overlap_ident: 75
  # hiere, we chose max_diffs high enough to rely on overlap identity only
  max_diffs: 1000

filter:
  max_error_rate: 0.002

# (optional, only needed if 'uparse' rule is run)
uparse:
  min_size: 2

# (optional, only needed if 'unoise3' rule is run)
unoise3:
  # lower to 4 for higher sensitivity, consider raising for very large datasets
  min_size: 8

otutab:
  ident_threshold: 97

# (optional, if 'sintax' rule is run)
sintax:
  db: refdb.fasta.gz
  db_format: qiime
  confidence: 0.7
